### ISSUE TITLE
Make the X's work

### ISSUE THREAD

**Issue by TheErikWolfe** [bootcamp-s18/php-palette-maker#1]
## Make the X's work
* When clicked under the color portion of the page, the X's should delete the color from both the page and the database.
* If an X is clicked next to a palette name it should delete the entire palette from both the page and the database.
* If an X is clicked next to a color under a palette it should only remove the color from the palette.

**Comment by TheErikWolfe** [comment]
Also, it'd be nice if the X's were red but that is just my ~~humble~~ opinion.

**Comment by emberborja** [comment]
I have an issue with your issue. You use the word "humble", but I'm not sure it means what you think it means.

**Comment by KarKunze** [comment]
I agree with the red and perhaps a html entity &timesb;?

**Comment by jhempy** [comment]
Closing this issue - it actually needs to be three separate issues.
